[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "music-score-editor"
version = "0.1.0"
dependencies = [
    "typer",
    "pypdf",
]

# [project.scripts]
# msc = "music_score_editor.main:app"
[project.scripts]
msc = "music_score_editor.cli:app"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]